# Copyright © 2025 artefox

import mcschematic
schem = mcschematic.MCSchematic()

mccode = open('output.mc', 'r') # HAS TO BE 2048 LINES
#out = open('temp.txt', 'w')
barrels = [
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:59b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:54b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:50b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:45b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:41b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:36b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:31b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:27b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:22b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:18b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:64b},{Slot:20b,id:"minecraft:redstone",Count:64b},{Slot:21b,id:"minecraft:redstone",Count:13b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:64b},{Slot:20b,id:"minecraft:redstone",Count:64b},{Slot:21b,id:"minecraft:redstone",Count:64b},{Slot:22b,id:"minecraft:redstone",Count:64b},{Slot:23b,id:"minecraft:redstone",Count:9b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:64b},{Slot:20b,id:"minecraft:redstone",Count:64b},{Slot:21b,id:"minecraft:redstone",Count:64b},{Slot:22b,id:"minecraft:redstone",Count:64b},{Slot:23b,id:"minecraft:redstone",Count:64b},{Slot:24b,id:"minecraft:redstone",Count:64b},{Slot:25b,id:"minecraft:redstone",Count:4b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:64b},{Slot:20b,id:"minecraft:redstone",Count:64b},{Slot:21b,id:"minecraft:redstone",Count:64b},{Slot:22b,id:"minecraft:redstone",Count:64b},{Slot:23b,id:"minecraft:redstone",Count:64b},{Slot:24b,id:"minecraft:redstone",Count:64b},{Slot:25b,id:"minecraft:redstone",Count:64b},{Slot:26b,id:"minecraft:redstone",Count:63b}]}',
    'minecraft:barrel[facing=up]{Items:[{Slot:0b,id:"minecraft:redstone",Count:64b},{Slot:1b,id:"minecraft:redstone",Count:64b},{Slot:2b,id:"minecraft:redstone",Count:64b},{Slot:3b,id:"minecraft:redstone",Count:64b},{Slot:4b,id:"minecraft:redstone",Count:64b},{Slot:5b,id:"minecraft:redstone",Count:64b},{Slot:6b,id:"minecraft:redstone",Count:64b},{Slot:7b,id:"minecraft:redstone",Count:64b},{Slot:8b,id:"minecraft:redstone",Count:64b},{Slot:9b,id:"minecraft:redstone",Count:64b},{Slot:10b,id:"minecraft:redstone",Count:64b},{Slot:11b,id:"minecraft:redstone",Count:64b},{Slot:12b,id:"minecraft:redstone",Count:64b},{Slot:13b,id:"minecraft:redstone",Count:64b},{Slot:14b,id:"minecraft:redstone",Count:64b},{Slot:15b,id:"minecraft:redstone",Count:64b},{Slot:16b,id:"minecraft:redstone",Count:64b},{Slot:17b,id:"minecraft:redstone",Count:64b},{Slot:18b,id:"minecraft:redstone",Count:64b},{Slot:19b,id:"minecraft:redstone",Count:64b},{Slot:20b,id:"minecraft:redstone",Count:64b},{Slot:21b,id:"minecraft:redstone",Count:64b},{Slot:22b,id:"minecraft:redstone",Count:64b},{Slot:23b,id:"minecraft:redstone",Count:64b},{Slot:24b,id:"minecraft:redstone",Count:64b},{Slot:25b,id:"minecraft:redstone",Count:64b},{Slot:26b,id:"minecraft:redstone",Count:64b}]}'
]

instructions = [line.strip() for line in mccode]


#output = [0] * (4 * n) # to bytes to barrels to columns aka all barrels     8192
output = [0] * (2048 * 8 * 2 // 4)

offset0 = pow(2, 3)
offset1 = pow(2, 2)
offset2 = pow(2, 1)
offset3 = pow(2, 0)

for k in range(8): # layer
    for j in range(16): # columns
        for i in range(32): # rows in pairs
            # (row * 16 * 4) + col + 16b
            byte0 = i * 64 + j
            byte1 = i * 64 + j + 16
            byte2 = i * 64 + j + 32
            byte3 = i * 64 + j + 48

            # row * 16 * 2 + col
            if i % 2 == 1: # alternate  H L  L H  H L  L H
                output[1024 * k + (i * 32 + j     )] = int(instructions[byte0][k    ])*offset0 + int(instructions[byte1][k    ])*offset1 + int(instructions[byte2][k    ])*offset2 + int(instructions[byte3][k    ])*offset3
                output[1024 * k + (i * 32 + j + 16)] = int(instructions[byte0][k + 8])*offset0 + int(instructions[byte1][k + 8])*offset1 + int(instructions[byte2][k + 8])*offset2 + int(instructions[byte3][k + 8])*offset3
            else:
                output[1024 * k + (i * 32 + j + 16)] = int(instructions[byte0][k    ])*offset0 + int(instructions[byte1][k    ])*offset1 + int(instructions[byte2][k    ])*offset2 + int(instructions[byte3][k    ])*offset3
                output[1024 * k + (i * 32 + j     )] = int(instructions[byte0][k + 8])*offset0 + int(instructions[byte1][k + 8])*offset1 + int(instructions[byte2][k + 8])*offset2 + int(instructions[byte3][k + 8])*offset3

for k in range(8):
    for j in range(16):
        for i in range(64):
            schem.setBlock((2 * j, (2 * -k)-1, 2 * i), barrels[output[1024 * k + 64 * j + i]])

print(len(output))

#out.write(f"{output}")
schem.save("schems", "rom", mcschematic.Version.JE_1_20_1)